### ISSUE TITLE
Can't get report portal to get data from testcafe

### ISSUE THREAD

**Issue by yllawwally** [danitseitlin/reportportal-testcafe-plugin#37]
When running the test, I get a message "Report Portal launch : function link() { [native code] }. No launch gets shown in report portal. 

At command line this is the command I am running. /usr/bin/node //home/wally/testcafe/node_modules/testscafe.js chrome test.js --reporter=reportportal --rdomain=http://reportportal.svcs.aws:8080/ --rtoken=xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --rlaunch=wally_test added --rproject=wally_test

**Comment by danitseitlin** [comment]
@Seems like you have a space between wally_test and added. Maybe add " ?

**Comment by yllawwally** [comment]
I added the quotes, and I'm still not seeing any results in report portal.

**Comment by danitseitlin** [comment]
@yllawwally The reporter is `reportportal-plugin`

**Comment by danitseitlin** [comment]
@yllawwally Your run should be: 
```
/usr/bin/node //home/wally/testcafe/node_modules/testscafe.js chrome test.js --reporter=reportportal-plugin --rdomain=reportportal.svcs.aws --rtoken=xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --rlaunch='wally_test_added' --rproject=wally_test
```
Let me know if this helps.

**Comment by yllawwally** [comment]
Thank you, it did help.  But now I'm at the next hurdle.  Connection error to reportportal
`/usr/bin/node //home/wally/testcafe/node_modules/testcafe/bin/testcafe.js chrome //home/wally/testcafe/tests/test.js --reporter=reportportal-plugin --rdomain=reportportal.svcs.aws:8080/ --rtoken=4edfb6e2-d638-4d15-be8e-e5df209ab46d --rlaunch='wally_test_added' --rproject=wally_test`

` Running tests in:
 - Chrome 92.0.4515.131 / Linux 0.0
Error connection to the Report Portal server
Error: write EPROTO 139779886016384:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at API.handleError (/home/wally/testcafe/node_modules/testcafe-reporter-reportportal-plugin/lib/api.js:204:11)
    at API.checkConnect (/home/wally/testcafe/node_modules/testcafe-reporter-reportportal-plugin/lib/api.js:28:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

 My First Fixture

ERROR The "reportTaskStart" method of the "reportportal-plugin" reporter produced an uncaught error. Error details:
Error: Report portal is not connected!
    at ReportPortal.startLaunch (/home/wally/testcafe/node_modules/testcafe-reporter-reportportal-plugin/lib/report-portal.js:53:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ReporterPluginHost.reportTaskStart (/home/wally/testcafe/node_modules/testcafe-reporter-reportportal-plugin/lib/index.js:18:7)
    at Reporter.dispatchToPlugin (/home/wally/testcafe/node_modules/testcafe/src/reporter/index.ts:278:13)
    at Reporter._onceTaskStartHandler (/home/wally/testcafe/node_modules/testcafe/src/reporter/index.ts:300:9)
    at /home/wally/testcafe/node_modules/testcafe/src/reporter/index.ts:424:40
    at async Promise.all (index 0)`

**Comment by danitseitlin** [comment]
@yllawwally It means there is no connection to the server, try passing --rprotocol=http in addition

**Comment by danitseitlin** [comment]
Also without the extra slash in the domain at the end.

**Comment by yllawwally** [comment]
I made the 2 recommended changes, and I still get an error. However, the error is now a 403.
`/usr/bin/node //home/wally/testcafe/node_modules/testcafe/bin/testcafe.js chrome //home/wally/testcafe/tests/test.js --reporter=reportportal-plugin --rdomain=reportportal.svcs.aws:8080 --rtoken=xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --rlaunch='wally_test_added' --rproject=wally_test --rprotocol=http`

` Running tests in:
 - Chrome 92.0.4515.131 / Linux 0.0
Error connection to the Report Portal server
Error: Request failed with status code 403
    at API.handleError (/home/wally/testcafe/node_modules/testcafe-reporter-reportportal-plugin/lib/api.js:204:11)
    at API.checkConnect (/home/wally/testcafe/node_modules/testcafe-reporter-reportportal-plugin/lib/api.js:28:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

 My First Fixture

ERROR The "reportTaskStart" method of the "reportportal-plugin" reporter produced an uncaught error. Error details:
Error: Report portal is not connected!
    at ReportPortal.startLaunch (/home/wally/testcafe/node_modules/testcafe-reporter-reportportal-plugin/lib/report-portal.js:53:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ReporterPluginHost.reportTaskStart (/home/wally/testcafe/node_modules/testcafe-reporter-reportportal-plugin/lib/index.js:18:7)
    at Reporter.dispatchToPlugin (/home/wally/testcafe/node_modules/testcafe/src/reporter/index.ts:278:13)
    at Reporter._onceTaskStartHandler (/home/wally/testcafe/node_modules/testcafe/src/reporter/index.ts:300:9)
    at /home/wally/testcafe/node_modules/testcafe/src/reporter/index.ts:424:40
    at async Promise.all (index 0)`

**Comment by danitseitlin** [comment]
@yllawwally Are you sure the token you're passing is correct? seems like it doesn't have enough permissions according to the error message: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

**Comment by yllawwally** [comment]
I'm listed as the project manager.  I regenerated my token, and tried it again.  But I saw no change in behavior.
![image](https://user-images.githubusercontent.com/34781859/130464772-2640e8da-cdd2-4f73-b10e-6b47f43040ac.png)

**Comment by yllawwally** [comment]
Hello sorry for taking so long to get back to you.  I can't run discord it's blocked, and can't get you access to the environment.  I regenerated the token.  I was able to make a curl in postman, that successfully connects to report portal, and can get information. I understand if you can't really help. 
Here is the working curl

 `curl -X GET \
  http://reportportal.svcs.aws:8080/api/v1/wally/launch \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer 115f95b4-XXXX-408d-9472-0d8764200911' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Host: reportportal.svcs.aws:8080' \
  -H 'Postman-Token: f6c79d60-01bc-4262-8d61-bb183be9c861,c26438ce-9aee-4ba4-9265-0d7b9586166d' \
  -H 'User-Agent: PostmanRuntime/7.15.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'filter.cnt.name: _TESTRUN_ON_LOCAL_ENV'`

**Comment by danitseitlin** [comment]
@yllawwally Hi, I did not forget you! I am just a bit overloaded with other project, 😅 
I promise to get to this soon :)

**Comment by yllawwally** [comment]
Not a problem, I understand.  I'm sorry I can't be more helpful with access.
